services:
  smartmeter:
    image: smartmeter
    container_name: smartmeter
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/smartmeter.conf:/etc/smartmeter.conf
    devices:
      - /dev/ttyUSB0
    # smartmeter:uucp
    user: 966:987
