{
 "title": "Smartmeter",
 "description": "Show data from a smart energy meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  energy\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Energy Today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', NOW()) as time,\n  last(energy, time) - first(energy, time) as energy_today\nFROM live\nWHERE\n  time > date_trunc('day', NOW())"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT                                                   \n  time,\n  power\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY time DESC LIMIT 1;"
    }
   ]
  },
  { "title": "Daily Energy", "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "Average Bill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS time,\n  avg(bill)\nFROM monthly_view"
    }
   ]
  },
  {
   "title": "Current Bill",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('month', NOW()) AS time,\n  sum(bill) AS bill\nFROM daily_view\nWHERE\n  time > date_trunc('month', NOW())"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  AVG(power_l1) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time,\n  AVG(power_l2) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time,\n  AVG(power_l3) OVER(ORDER BY time ROWS BETWEEN 4 PRECEDING AND CURRENT ROW)\nFROM live\nWHERE\n  $__timeFilter(time)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Monthly Energy",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_1m AS time,\n  energy\nFROM monthly_view\nWHERE\n  $__timeFilter(bucket_1m)\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  bucket_1m AS time,\n  bill\nFROM monthly_view\nWHERE\n  $__timeFilter(bucket_1m)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  bucket_5m AS time,\n  power_5m AS power\nFROM cagg_power\nWHERE\n  $__timeFilter(bucket_5m)\nORDER BY 1"
    }
   ]
  }
 ]
}